version: '3.8'
services:
  app:
    build:
      context: .
    image: pp-backend
    user: "1000:1000"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "256m"
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: always
    environment:
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=no.reply.cert.repo@gmail.com
      - SPRING_MAIL_PASSWORD=
      - APP_PORT=${APP_PORT}
    networks:
      - default
volumes:
  postgres_data:

networks:
  default: { }
